keys:
  - &gpg_tulip_default F0A7BB97CAF49D8CB058BB0A744FDDD73AECC993
  - &host_key REPLACE_INVALID

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *gpg_tulip_default
        age:
          - *host_key
  - path_regex: secrets/files/.*/.*$
    key_groups:
      - pgp:
          - *gpg_tulip_default
        age:
          - *host_key

stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
