# DISK
# Customize disk allocation
# Strings are sorted by their time of execution.
# x%FREE means x% of what is left after allocating the previous volume.
#                /        /nix      /var      /home
DISK_ALLOCATION=("5%FREE" "30%FREE" "50%FREE" "100%FREE")

# SUBVOLUMES and matching CONFIG name
# Only subvolumes (except /) in /var /nix /home are allowed
SUBVOLUMES=("/" "/nix/" "/var/" "/var/lib/" "/var/lib/docker/" "/var/lib/flatpak/" "/var/lib/libvirt/" "/var/lib/mysql/" "/var/cache/" "/var/games/" "/var/log/" "/home/")
CONFIGS=("root" "nix" "var" "var_lib" "var_lib_docker" "var_lib_flatpak" "var_lib_libvirt" "var_lib_mysql" "var_cache" "var_games" "var_log" "home")
